BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "uptime_server" (
	"YEAR"	INTEGER NOT NULL,
	"MONTH"	INTEGER NOT NULL,
	"TICKS"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "uptime_client" (
	"NODE"	TEXT NOT NULL,
	"YEAR"	INTEGER NOT NULL,
	"MONTH"	INTEGER NOT NULL,
	"TICKS"	INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS "INDEX_YEAR_SERVER" ON "uptime_server" (
	"YEAR"
);
CREATE INDEX IF NOT EXISTS "INDEX_MONTH_SERVER" ON "uptime_server" (
	"MONTH"
);
CREATE INDEX IF NOT EXISTS "INDEX_NODE_CLIENT" ON "uptime_client" (
	"NODE"
);
CREATE INDEX IF NOT EXISTS "INDEX_YEAR_CLIENT" ON "uptime_client" (
	"YEAR"
);
CREATE INDEX IF NOT EXISTS "INDEX_MONTH_CLIENT" ON "uptime_client" (
	"MONTH"
);
COMMIT;
